@startuml HealthcareSystem_Microservices_SingleDB_NoGateway

actor "Patient" as patient
actor "Physician" as physician
actor "Administrator" as admin

rectangle "Healthcare Management System" {

    rectangle "Patient Service" as patientService
    rectangle "Physician Service" as physicianService
    rectangle "Appointment Service" as appointmentService

    database "Healthcare Database" as db
}

patient --> patientService : Register/Login and Profile Management
physician --> physicianService : Login/Scheduling
admin --> appointmentService : Scheduling Management

appointmentService --> patientService : Verifica paciente registado
appointmentService --> physicianService : Verifica disponibilidade médico

patientService --> db : CRUD Pacientes
physicianService --> db : CRUD Médicos
appointmentService --> db : CRUD Consultas

@enduml