@startuml

actor "Patient" as patient
actor "Physician" as physician
actor "Administrator" as admin

rectangle "Healthcare Management System" {

    rectangle "Patient Service" as patientService
    rectangle "Physician Service" as physicianService
    rectangle "Appointment Service" as appointmentService

    database "Patient Database" as patientDB
    database "Physician Database" as physicianDB
    database "Appointment Database" as appointmentDB

}

patient --> patientService : Register/Login and Profile Management
physician --> physicianService : Login/Scheduling
admin --> appointmentService : Scheduling Management

appointmentService --> patientService : Verifica paciente registado
appointmentService --> physicianService : Verifica disponibilidade médico

patientService --> patientDB : CRUD Pacientes
physicianService --> physicianDB : CRUD Médicos
appointmentService --> appointmentDB : CRUD Consultas

@enduml