@startuml C4 Deployment Diagram - With API Gateway and RabbitMQ

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

title VF2 — API Gateway, Auth, Services, RabbitMQ e Nginx


Deployment_Node(NginxNode, "Nginx Reverse Proxy", "Nginx", "Ponto de entrada externo. Faz proxy para o API Gateway.") {
    Container(NginxService, "Nginx", "Reverse Proxy", "Encaminha chamadas externas para o API Gateway")
}


Deployment_Node(APIGatewayNode, "API Gateway", "Spring Cloud Gateway", "Ponto de entrada interno para roteamento de chamadas.") {
    Container(APIGateway, "API Gateway", "Router/Proxy", "Responsável por rotear chamadas para o Auth Service e para os outros microserviços.")
}


Deployment_Node(AuthServiceNode, "Auth Service", "Spring Boot", "Serviço responsável pela autenticação e autorização.") {
    Container(AuthController, "Auth Controller", "REST API", "Expõe /api/auth para login, validação de tokens, etc.")
    ContainerDb(AuthDB, "Auth Database", "PostegreSQL database", "Armazena utilizadores, roles, tokens revogados, etc.")
}


Deployment_Node(AppointmentServiceNode, "Appointment Service", "Spring Boot", "Ambiente do serviço de consultas.") {
    Container(AppointmentController, "Appointment Controller", "REST API", "Expõe a API (/api/appointments).")
    ContainerDb(AppointmentDB, "Appointment Database", "H2 database", "Armazena dados das consultas.")
}


Deployment_Node(PatientServiceNode, "Patient Service", "Spring Boot", "Ambiente do serviço de Pacientes.") {
    Container(PatientController, "Patient Controller", "REST API", "Expõe a API (/api/patients).")
    ContainerDb(PatientDB, "Patient Database", "H2 database", "Armazena dados de Pacientes.")
}


Deployment_Node(PhysicianServiceNode, "Physicians Service", "Spring Boot", "Ambiente do serviço de Physicians.") {
    Container(PhysicianController, "Physician Controller", "REST API", "Expõe a API (/api/physicians).")
    ContainerDb(PhysicianDB, "Physician Database", "H2 database", "Armazena dados de Physicians.")
}


Deployment_Node(RabbitMQNode, "RabbitMQ Broker", "RabbitMQ", "Message broker para comunicação assíncrona entre serviços.") {
    Container(RabbitMQBroker, "RabbitMQ", "Message Broker (AMQP)", "Comunicação Assíncrona")
}


Rel(NginxService, APIGateway, "Forward externo / Reverse Proxy", "HTTP/REST")

Rel(APIGatewayNode, AuthServiceNode, "Routing para Auth Service", "HTTP/REST")
Rel_Right(APIGatewayNode, PatientServiceNode, "Routing para Patient Service", "HTTP/REST")
Rel_Down(APIGatewayNode, PhysicianServiceNode, "Routing para Physicians Service", "HTTP/REST")

Rel(AuthServiceNode, AppointmentServiceNode, "Validação de token / autorização", "HTTP/REST")


Rel(PatientController, PatientDB, "Lê e Escreve", "JDBC")
Rel(PhysicianController, PhysicianDB, "Lê e Escreve", "JDBC")
Rel_Right(AppointmentController, AppointmentDB, "Lê e Escreve", "JDBC")
Rel(AuthController, AuthDB, "Lê e Escreve", "JDBC")


Rel(AppointmentServiceNode, RabbitMQNode, "Publica/Consome eventos CREATE/UPDATE/DELETE", "AMQP")
Rel(PatientServiceNode, RabbitMQNode, "Publica/Consome eventos CREATE/UPDATE/DELETE", "AMQP")
Rel(PhysicianServiceNode, RabbitMQNode, "Publica/Consome eventos CREATE/UPDATE/DELETE", "AMQP")
Rel(AuthServiceNode, RabbitMQNode, "Publica/Consome eventos CREATE/UPDATE/DELETE", "AMQP")

@enduml