@startuml
title C3 — HAP (Healthcare Administration Platform) — Component Diagram for Appointment Service

skinparam shadowing false
skinparam rectangleBorderThickness 1
skinparam databaseBorderThickness 1
skinparam componentStyle rectangle

skinparam rectangle {
    BackgroundColor #85BBF0
    BorderColor #438DD5
    FontColor #000000
}
skinparam database {
    BackgroundColor #61B329
    BorderColor #000000
}
skinparam actor {
    BackgroundColor #08427B
    BorderColor #000000
    FontColor #FFFFFF
}


rectangle "Physician Service" as physician_svc
rectangle "Patient Service" as patient_svc
rectangle "RabbitMQConfig\n[Spring Configuration]\n\nDefines data flux and Bindings." as rabbitmq_config
rectangle "Authentication Service\n[JWT Validation]\n\nCreates JWT Tokens for Instance Validation." as jwt


frame "Appointment Service [container]" {

    rectangle "AppointmentController\n[Spring REST Controller]\n\nReceives HTTP requests from the\nGateway and other peers." as controller
    rectangle "SecurityConfig\n[Spring Security]\n\nSecures endpoints (e.g., /api/*)." as security
    rectangle "AppointmentRepository\n[Spring Data JPA Interface]\n\nAccesses the local Appointment DB." as repository
    database "Appointment DB" as appointment_db

}

controller -down-> repository : "Uses Repository"
security -right-> controller : "Secures"
repository -down-> appointment_db : "Reads from and writes to\n[JDBC]"

controller -right-> rabbitmq_config : "To update Patient and Physician Service data\n[Message Broker]"
rabbitmq_config -down-> patient_svc : "Patient Event from\n Appointment Service"
rabbitmq_config -down-> physician_svc : "Physician Event from\n Appointment Service"
jwt -left-> controller : "Creates JWT Token for Appointment Service"

@enduml