@startuml C1-HAP-Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title C1 — Healthcare Administration Platform (Context View - C1)

Person(doctor, "Doctor", "Checks schedule and registers clinic data")
Person(staff, "Staff/Admin", "Manages pacients, doctors and schedules")

System_Boundary(hap, "Healthcare Administration Platform") {
  System(hap_api, "HAP", "APIs REST for Doctors and Pacients")
}

Rel(doctor, hap_api, "Usa", "HTTPS/REST")
Rel(staff,  hap_api, "Usa", "HTTPS/REST")

@enduml
